"""empty message

Revision ID: d164a7bf4fe0
Revises: 68859de65769
Create Date: 2023-02-15 23:16:09.502422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd164a7bf4fe0'
down_revision = '68859de65769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if environment == "production":
        op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE;")
        op.execute(f"CREATE SCHEMA {SCHEMA};")
        op.execute(f"SET search_path TO {SCHEMA},public;")

    op.drop_table('followers')
    # ### end Alembic commands ###

    if environment == "production":
        op.execute(f"ALTER TABLE followers SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###
