"""empty message

Revision ID: 68859de65769
Revises: ffdc0a98111c
Create Date: 2023-02-15 22:05:39.258821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68859de65769'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    if environment == "production":
        op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE;")
        op.execute(f"CREATE SCHEMA {SCHEMA};")
        op.execute(f"SET search_path TO {SCHEMA},public;")

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE followers SET SCHEMA {SCHEMA};")

    op.add_column('users', sa.Column('firstName', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('image', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_table('followers')
    # ### end Alembic commands ###
